spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
    username: root
    password: rafad18m01
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
